import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv(r"C:\Users\kathiravan\OneDrive\Desktop\team 15\retail store\retail_store_sales.csv")
print("Dataset loaded successfully")
print("\nShape of dataset (rows, columns):")
print(df.shape)
print("\nColumn names:")
print(df.columns)
print("\nFirst 5 rows:")
print(df.head())
print("\nLast 5 rows:")
print(df.tail())
print("\nDataset info:")
print(df.info())
print("\nData types:")
print(df.dtypes)
print("\nMissing values in each column:")
print(df.isnull().sum())
print("\nStatistical summary:")
print(df.describe())
print("\nUnique items:")
print(df['Item'].unique())
print("\nPayment method count:")
print(df['Payment Method'].value_counts())
print("\nLocation count:")
print(df['Location'].value_counts())
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])
print("Dataset contains missing values that require preprocessing.")
print("Contains numerical and categorical data.")
print("Suitable for data preprocessing and analysis.")